// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class TestInfo;
class TestInfos;

// ===================================================================

class TestInfo : public ::google::protobuf::Message {
 public:
  TestInfo();
  virtual ~TestInfo();

  TestInfo(const TestInfo& from);

  inline TestInfo& operator=(const TestInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestInfo& default_instance();

  void Swap(TestInfo* other);

  // implements Message ----------------------------------------------

  TestInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestInfo& from);
  void MergeFrom(const TestInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // optional string str = 2;
  inline bool has_str() const;
  inline void clear_str();
  static const int kStrFieldNumber = 2;
  inline const ::std::string& str() const;
  inline void set_str(const ::std::string& value);
  inline void set_str(const char* value);
  inline void set_str(const char* value, size_t size);
  inline ::std::string* mutable_str();
  inline ::std::string* release_str();
  inline void set_allocated_str(::std::string* str);

  // optional int32 opt = 3;
  inline bool has_opt() const;
  inline void clear_opt();
  static const int kOptFieldNumber = 3;
  inline ::google::protobuf::int32 opt() const;
  inline void set_opt(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TestInfo)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_str();
  inline void clear_has_str();
  inline void set_has_opt();
  inline void clear_has_opt();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 id_;
  ::std::string* str_;
  ::google::protobuf::int32 opt_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static TestInfo* default_instance_;
};
// -------------------------------------------------------------------

class TestInfos : public ::google::protobuf::Message {
 public:
  TestInfos();
  virtual ~TestInfos();

  TestInfos(const TestInfos& from);

  inline TestInfos& operator=(const TestInfos& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestInfos& default_instance();

  void Swap(TestInfos* other);

  // implements Message ----------------------------------------------

  TestInfos* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestInfos& from);
  void MergeFrom(const TestInfos& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .TestInfo infos = 1;
  inline int infos_size() const;
  inline void clear_infos();
  static const int kInfosFieldNumber = 1;
  inline const ::TestInfo& infos(int index) const;
  inline ::TestInfo* mutable_infos(int index);
  inline ::TestInfo* add_infos();
  inline const ::google::protobuf::RepeatedPtrField< ::TestInfo >&
      infos() const;
  inline ::google::protobuf::RepeatedPtrField< ::TestInfo >*
      mutable_infos();

  // @@protoc_insertion_point(class_scope:TestInfos)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::TestInfo > infos_;
  friend void  protobuf_AddDesc_test_2eproto();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
  static TestInfos* default_instance_;
};
// ===================================================================


// ===================================================================

// TestInfo

// optional int64 id = 1;
inline bool TestInfo::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestInfo::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestInfo::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 TestInfo::id() const {
  // @@protoc_insertion_point(field_get:TestInfo.id)
  return id_;
}
inline void TestInfo::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TestInfo.id)
}

// optional string str = 2;
inline bool TestInfo::has_str() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TestInfo::set_has_str() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TestInfo::clear_has_str() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TestInfo::clear_str() {
  if (str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    str_->clear();
  }
  clear_has_str();
}
inline const ::std::string& TestInfo::str() const {
  // @@protoc_insertion_point(field_get:TestInfo.str)
  return *str_;
}
inline void TestInfo::set_str(const ::std::string& value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    str_ = new ::std::string;
  }
  str_->assign(value);
  // @@protoc_insertion_point(field_set:TestInfo.str)
}
inline void TestInfo::set_str(const char* value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    str_ = new ::std::string;
  }
  str_->assign(value);
  // @@protoc_insertion_point(field_set_char:TestInfo.str)
}
inline void TestInfo::set_str(const char* value, size_t size) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    str_ = new ::std::string;
  }
  str_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TestInfo.str)
}
inline ::std::string* TestInfo::mutable_str() {
  set_has_str();
  if (str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    str_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:TestInfo.str)
  return str_;
}
inline ::std::string* TestInfo::release_str() {
  clear_has_str();
  if (str_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = str_;
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TestInfo::set_allocated_str(::std::string* str) {
  if (str_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete str_;
  }
  if (str) {
    set_has_str();
    str_ = str;
  } else {
    clear_has_str();
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:TestInfo.str)
}

// optional int32 opt = 3;
inline bool TestInfo::has_opt() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TestInfo::set_has_opt() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TestInfo::clear_has_opt() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TestInfo::clear_opt() {
  opt_ = 0;
  clear_has_opt();
}
inline ::google::protobuf::int32 TestInfo::opt() const {
  // @@protoc_insertion_point(field_get:TestInfo.opt)
  return opt_;
}
inline void TestInfo::set_opt(::google::protobuf::int32 value) {
  set_has_opt();
  opt_ = value;
  // @@protoc_insertion_point(field_set:TestInfo.opt)
}

// -------------------------------------------------------------------

// TestInfos

// repeated .TestInfo infos = 1;
inline int TestInfos::infos_size() const {
  return infos_.size();
}
inline void TestInfos::clear_infos() {
  infos_.Clear();
}
inline const ::TestInfo& TestInfos::infos(int index) const {
  // @@protoc_insertion_point(field_get:TestInfos.infos)
  return infos_.Get(index);
}
inline ::TestInfo* TestInfos::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:TestInfos.infos)
  return infos_.Mutable(index);
}
inline ::TestInfo* TestInfos::add_infos() {
  // @@protoc_insertion_point(field_add:TestInfos.infos)
  return infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TestInfo >&
TestInfos::infos() const {
  // @@protoc_insertion_point(field_list:TestInfos.infos)
  return infos_;
}
inline ::google::protobuf::RepeatedPtrField< ::TestInfo >*
TestInfos::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:TestInfos.infos)
  return &infos_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
